# ClusterIP Service (internal only)
apiVersion: v1
kind: Service
metadata:
  name: my-app-internal
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80

---
# LoadBalancer Service (external access)
apiVersion: v1
kind: Service
metadata:
  name: my-app-external
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80

---
# NodePort Service (development/testing)
apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
